// Package commands — sprint family registry entries.
package commands

func buildSprintCommand() Command {
	return Command{
		Name:          "sprint",
		Aliases:       []string{"s"},
		Summary:       "Manage sprints and their task membership/ordering.",
		Description:   "Create, list, query, mutate, and order sprints and their task assignments.",
		HelpPrinter:   printSprintHelp,
		HasSubcommand: true,
		Prerequisites: []string{"An existing roadmap selected via -r/--roadmap."},
		Subcommands: []Subcommand{
			{
				Name: "list", Aliases: []string{"ls"},
				Summary:     "List sprints.",
				Description: "Lists every sprint in the roadmap, optionally filtered by status.",
				Usage:       "rmp sprint list -r <roadmap> [--status <state>]",
				HelpPrinter: printSprintListHelp,
				Handler:     sprintList,
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--status", Type: "enum", Enum: "SprintStatus", Description: "Filter by sprint status."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of sprint objects."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 6},
				Examples: []Example{
					{Title: "All sprints", Cmd: "rmp sprint list -r myproject", Exit: 0},
					{Title: "Invalid status filter", Cmd: "rmp sprint list -r myproject --status INVALID", Stderr: "Error: validation error: invalid sprint status: \"INVALID\": invalid sprint status", Exit: 6},
				},
			},
			{
				Name: "create", Aliases: []string{"new"},
				Summary:     "Create a new sprint (PENDING).",
				Description: "Creates a new sprint in PENDING status.",
				Usage:       "rmp sprint create -r <roadmap> -t <title> -d <description> [--max-tasks <n>] [--order <n>]",
				HelpPrinter: printSprintCreateHelp,
				Handler:     sprintCreate,
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--title", Short: "-t", Type: "string", Required: true, MaxLength: 255, Description: "Sprint title."},
					{Long: "--description", Short: "-d", Type: "string", Required: true, MaxLength: 2048, Description: "Sprint description. Must state the high-level (macro) goal of the development effort the sprint delivers: a new development, a fix, a refactoring, or another kind of change. Together with the title, it must give a human or an AI agent a clear macro idea of what the sprint's tasks are specifically aimed at. Detailed scope, technical detail, and acceptance conditions belong in the sprint's tasks, not here."},
					{Long: "--max-tasks", Type: "integer", HasRange: true, RangeMin: 1, RangeMax: 10000, Description: "Capacity cap on active tasks; cannot be removed once set."},
					{Long: "--order", Type: "integer", HasRange: true, RangeMin: 1, Description: "Sprint execution order; positive integer (> 0), unique across the roadmap. Optional: auto-assigned to the highest existing order plus one when omitted. A value already used by another sprint is rejected with exit code 5."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "object", Schema: `{"id": <int>}`, Example: `{"id":1}`},
				SideEffects: SideEffects{Database: "INSERT into sprints + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 2, 3, 5, 6},
				Examples: []Example{
					{Title: "Create", Cmd: `rmp sprint create -r myproject -t "Authentication hardening" -d "Deliver session-based authentication for every write command."`, Stdout: `{"id":1}`, Exit: 0},
					{Title: "Missing required title", Cmd: `rmp sprint create -r myproject -d "Deliver session-based authentication for every write command."`, Stderr: "Error: required parameter missing: --title", Exit: 2},
				},
			},
			{
				Name:        "get",
				Summary:     "Get sprint details (sprint object only).",
				Description: "Returns the sprint object for <sprint-id>.",
				Usage:       "rmp sprint get -r <roadmap> <sprint-id>",
				HelpPrinter: printSprintGetHelp,
				Handler:     sprintGet,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "object", Schema: "Single sprint object."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Get sprint", Cmd: "rmp sprint get -r myproject 5", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint get -r myproject 99999", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name:        "show",
				Summary:     "Stand-up-style summary (counts, distributions).",
				Description: "Returns a stand-up summary of the sprint with task counts and per-severity distributions.",
				Usage:       "rmp sprint show -r <roadmap> <sprint-id>",
				HelpPrinter: printSprintShowHelp,
				Handler:     sprintShow,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "object", Schema: "{sprint_id, sprint_title, sprint_description, status, max_tasks, capacity_pct, current_load, task_order, summary, progress, severity_distribution, criticality_distribution}"},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Show", Cmd: "rmp sprint show -r myproject 5", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint show -r myproject 99999", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name: "update", Aliases: []string{"upd"},
				Summary:     "Update sprint title, description, capacity cap or execution order.",
				Description: "Edits the title, description, capacity cap or execution order of an existing sprint. At least one option required.",
				Usage:       "rmp sprint update -r <roadmap> <sprint-id> [-t <title>] [-d <text>] [--max-tasks <n>] [--order <n>]",
				HelpPrinter: printSprintUpdateHelp,
				Handler:     sprintUpdate,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--title", Short: "-t", Type: "string", MaxLength: 255, Description: "New title."},
					{Long: "--description", Short: "-d", Type: "string", MaxLength: 2048, Description: "New sprint description. Carries the same semantics as on create: it must state the high-level (macro) goal of the development effort the sprint delivers: a new development, a fix, a refactoring, or another kind of change. Together with the title, it must give a human or an AI agent a clear macro idea of what the sprint's tasks are specifically aimed at. Detailed scope, technical detail, and acceptance conditions belong in the sprint's tasks, not here."},
					{Long: "--max-tasks", Type: "integer", HasRange: true, RangeMin: 1, RangeMax: 10000, Description: "New capacity cap."},
					{Long: "--order", Type: "integer", HasRange: true, RangeMin: 1, Description: "New sprint execution order; positive integer (> 0), unique across the roadmap. Allowed only while the sprint is PENDING or OPEN; once CLOSED the order is immutable and a change is rejected with exit code 6. A value already used by another sprint is rejected with exit code 5."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprints + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 2, 3, 4, 5, 6},
				Examples: []Example{
					{Title: "Update description", Cmd: `rmp sprint update -r myproject 5 -d "Deliver authentication and request tracing for every write command."`, Exit: 0},
					{Title: "Sprint not found", Cmd: `rmp sprint update -r myproject 99999 -d "Refactor persistence onto a single write path."`, Stderr: "Error: resource not found: sprint 99999 not found", Exit: 4},
				},
			},
			{
				Name: "remove", Aliases: []string{"rm"},
				Summary:     "Delete sprint (member tasks revert to BACKLOG).",
				Description: "Deletes the sprint; member tasks revert to BACKLOG (not deleted).",
				Usage:       "rmp sprint remove -r <roadmap> <sprint-id>",
				HelpPrinter: printSprintRemoveHelp,
				Handler:     sprintRemove,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "DELETE sprint + UPDATE tasks + audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Remove sprint", Cmd: "rmp sprint remove -r myproject 5", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint remove -r myproject 99999", Stderr: "Error: resource not found: sprint 99999 not found", Exit: 4},
				},
			},
			{
				Name:        "start",
				Summary:     "PENDING -> OPEN (sets started_at).",
				Description: "Transitions a sprint from PENDING to OPEN. Only one sprint can be OPEN at a time.",
				Usage:       "rmp sprint start -r <roadmap> <sprint-id>",
				HelpPrinter: printSprintStartHelp,
				Handler:     sprintStart,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprints + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Start sprint", Cmd: "rmp sprint start -r myproject 5", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint start -r myproject 99999", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name:        "close",
				Summary:     "OPEN -> CLOSED (--force bypasses active-task check).",
				Description: "Transitions an OPEN sprint to CLOSED; rejects active tasks unless --force given.",
				Usage:       "rmp sprint close -r <roadmap> <sprint-id> [--force]",
				HelpPrinter: printSprintCloseHelp,
				Handler:     sprintClose,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--force", Type: "boolean", Description: "Close even when SPRINT/DOING/TESTING tasks remain (prints warning to stderr)."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprints + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Close clean", Cmd: "rmp sprint close -r myproject 5", Exit: 0},
					{Title: "Force close", Cmd: "rmp sprint close -r myproject 5 --force", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint close -r myproject 99999", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name:        "reopen",
				Summary:     "CLOSED -> OPEN (clears closed_at; started_at preserved).",
				Description: "Transitions a CLOSED sprint back to OPEN. Rejected if another sprint is already OPEN.",
				Usage:       "rmp sprint reopen -r <roadmap> <sprint-id>",
				HelpPrinter: printSprintReopenHelp,
				Handler:     sprintReopen,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprints + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Reopen", Cmd: "rmp sprint reopen -r myproject 5", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint reopen -r myproject 99999", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name:        "tasks",
				Summary:     "List ALL tasks in sprint (incl. COMPLETED).",
				Description: "Lists every task assigned to <sprint-id>, regardless of status, optionally filtered by exact task status.",
				Usage:       "rmp sprint tasks -r <roadmap> <sprint-id> [-s <state>] [--order-by-priority]",
				HelpPrinter: printSprintTasksHelp,
				Handler:     sprintTasks,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--status", Short: "-s", Type: "enum", Enum: "TaskStatus", Description: "Filter by exact task status (BACKLOG, SPRINT, DOING, TESTING, COMPLETED)."},
					{Long: "--order-by-priority", Type: "boolean", Description: "Re-sort by priority DESC; default is sprint position ASC."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "All sprint tasks", Cmd: "rmp sprint tasks -r myproject 5", Exit: 0},
					{Title: "Filter by status", Cmd: "rmp sprint tasks -r myproject 5 -s DOING", Exit: 0},
					{Title: "Invalid status", Cmd: "rmp sprint tasks -r myproject 5 -s INVALID", Stderr: "Error: validation error: invalid task status: \"INVALID\": invalid task status", Exit: 6},
				},
			},
			{
				Name:        "open-tasks",
				Summary:     "List incomplete tasks in sprint (SPRINT, DOING, TESTING).",
				Description: "Lists incomplete tasks in <sprint-id> (status SPRINT, DOING, or TESTING).",
				Usage:       "rmp sprint open-tasks -r <roadmap> <sprint-id> [--order-by-priority]",
				HelpPrinter: printSprintOpenTasksHelp,
				Handler:     sprintOpenTasks,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--order-by-priority", Type: "boolean", Description: "Sort by priority DESC; otherwise sprint position."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects (excludes BACKLOG/COMPLETED)."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Open tasks", Cmd: "rmp sprint open-tasks -r myproject 5", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint open-tasks -r myproject 99999", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name:        "stats",
				Summary:     "Per-status counts, burndown, velocity, days_*.",
				Description: "Returns SprintStats: per-status counts, burndown, velocity, elapsed days.",
				Usage:       "rmp sprint stats -r <roadmap> <sprint-id>",
				HelpPrinter: printSprintStatsHelp,
				Handler:     sprintStats,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "object", Schema: "SprintStats object."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Stats", Cmd: "rmp sprint stats -r myproject 5", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint stats -r myproject 99999", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name: "add-tasks", Aliases: []string{"add"},
				Summary:     "Atomically add BACKLOG tasks -> SPRINT.",
				Description: "Atomically moves listed tasks into <sprint-id> and flips status BACKLOG -> SPRINT.",
				Usage:       "rmp sprint add-tasks -r <roadmap> <sprint-id> <task-ids>",
				HelpPrinter: printSprintAddTasksHelp,
				Handler:     sprintAddTasks,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id (must not be CLOSED)."},
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer task ids."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "INSERT sprint_tasks + UPDATE tasks + audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Add tasks", Cmd: "rmp sprint add-tasks -r myproject 5 1,3,7", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint add-tasks -r myproject 99999 1", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name: "remove-tasks", Aliases: []string{"rm-tasks"},
				Summary:     "Remove tasks from sprint (revert to BACKLOG).",
				Description: "Removes listed tasks from the sprint and flips status back to BACKLOG.",
				Usage:       "rmp sprint remove-tasks -r <roadmap> <sprint-id> <task-ids>",
				HelpPrinter: printSprintRemoveTasksHelp,
				Handler:     sprintRemoveTasks,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer task ids."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "DELETE sprint_tasks + UPDATE tasks + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Remove tasks", Cmd: "rmp sprint remove-tasks -r myproject 5 1,3,7", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint remove-tasks -r myproject 99999 1", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name: "move-tasks", Aliases: []string{"mv-tasks"},
				Summary:     "Move tasks between sprints (status preserved).",
				Description: "Moves tasks from one sprint to another in a single transaction.",
				Usage:       "rmp sprint move-tasks -r <roadmap> <from-id> <to-id> <task-ids>",
				HelpPrinter: printSprintMoveTasksHelp,
				Handler:     sprintMoveTasks,
				Positional: []Argument{
					{Name: "from-id", Type: "integer", Required: true, Description: "Source sprint id."},
					{Name: "to-id", Type: "integer", Required: true, Description: "Destination sprint id."},
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer task ids."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprint_tasks + audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Move", Cmd: "rmp sprint move-tasks -r myproject 5 8 3,7", Exit: 0},
					{Title: "Source sprint not found", Cmd: "rmp sprint move-tasks -r myproject 99999 8 1", Stderr: "Error: resource not found: from sprint: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name: "reorder", Aliases: []string{"order"},
				Summary:     "Set exact full ordering (all members in CSV).",
				Description: "Sets the exact ordering of tasks within <sprint-id>. List must include every task.",
				Usage:       "rmp sprint reorder -r <roadmap> <sprint-id> <task-ids>",
				HelpPrinter: printSprintReorderHelp,
				Handler:     sprintReorder,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated task ids in the desired order."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprint_tasks positions + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Reorder", Cmd: "rmp sprint reorder -r myproject 5 3,1,7,2", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint reorder -r myproject 99999 1", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name: "move-to", Aliases: []string{"mvto"},
				Summary:     "Move one task to zero-based position.",
				Description: "Moves a single task to an exact position within the sprint (0-based).",
				Usage:       "rmp sprint move-to -r <roadmap> <sprint-id> <task-id> <position>",
				HelpPrinter: printSprintMoveToHelp,
				Handler:     sprintMoveTo,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer id of the task to move."},
					{Name: "position", Type: "integer", Required: true, Description: "Zero-based target index."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprint_tasks positions + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Move to top", Cmd: "rmp sprint move-to -r myproject 5 7 0", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint move-to -r myproject 99999 1 0", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name:        "swap",
				Summary:     "Swap positions of two tasks.",
				Description: "Exchanges the positions of two tasks within the same sprint.",
				Usage:       "rmp sprint swap -r <roadmap> <sprint-id> <task-id-1> <task-id-2>",
				HelpPrinter: printSprintSwapHelp,
				Handler:     sprintSwap,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
					{Name: "task-id-1", Type: "integer", Required: true, Description: "Integer id of first task."},
					{Name: "task-id-2", Type: "integer", Required: true, Description: "Integer id of second task (must differ)."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprint_tasks positions + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Swap", Cmd: "rmp sprint swap -r myproject 5 3 7", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint swap -r myproject 99999 1 2", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name:        "top",
				Summary:     "Move task to position 0.",
				Description: "Moves a single task to the top of the sprint (position 0).",
				Usage:       "rmp sprint top -r <roadmap> <sprint-id> <task-id>",
				HelpPrinter: printSprintTopHelp,
				Handler:     sprintTop,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer id of the task."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprint_tasks positions + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Top", Cmd: "rmp sprint top -r myproject 5 7", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint top -r myproject 99999 7", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
			{
				Name: "bottom", Aliases: []string{"btm"},
				Summary:     "Move task to last position.",
				Description: "Moves a single task to the last position of the sprint.",
				Usage:       "rmp sprint bottom -r <roadmap> <sprint-id> <task-id>",
				HelpPrinter: printSprintBottomHelp,
				Handler:     sprintBottom,
				Positional: []Argument{
					{Name: "sprint-id", Type: "integer", Required: true, Description: "Integer sprint id."},
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer id of the task."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE sprint_tasks positions + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Bottom", Cmd: "rmp sprint bottom -r myproject 5 7", Exit: 0},
					{Title: "Sprint not found", Cmd: "rmp sprint bottom -r myproject 99999 7", Stderr: "Error: resource not found: sprint 99999", Exit: 4},
				},
			},
		},
	}
}
