// Package commands — task family registry entries.
package commands

// taskTextFlags returns the shared title / requirements flag set used
// by `task create` (all required) and `task edit` (all optional). The
// caller flips Required as appropriate.
func taskTextFlags(required bool) []Flag {
	return []Flag{
		{Long: "--title", Short: "-t", Type: "string", Required: required, MaxLength: 255, Description: "Task title."},
		{Long: "--functional-requirements", Short: "-fr", Type: "string", Required: required, MaxLength: 4096, Description: "Why? Functional requirements."},
		{Long: "--technical-requirements", Short: "-tr", Type: "string", Required: required, MaxLength: 4096, Description: "How? Technical description."},
		{Long: "--acceptance-criteria", Short: "-ac", Type: "string", Required: required, MaxLength: 4096, Description: "How to verify? Completion criteria."},
	}
}

// taskCommonOptionalFlags returns the optional task fields shared
// across create and edit.
func taskCommonOptionalFlags() []Flag {
	return []Flag{
		{Long: "--type", Short: "-y", Type: "enum", Enum: "TaskType", Default: "TASK", Description: "Task type."},
		{Long: "--priority", Short: "-p", Type: "integer", HasRange: true, RangeMin: 0, RangeMax: 9, Default: "0", Description: "Priority (0 lowest, 9 highest)."},
		{Long: "--severity", Type: "integer", HasRange: true, RangeMin: 0, RangeMax: 9, Default: "0", Description: "Severity (0 lowest, 9 highest)."},
		{Long: "--specialists", Short: "-sp", Type: "list:string", MaxLength: 500, Description: "Comma-separated specialists."},
	}
}

func buildTaskCommand() Command {
	return Command{
		Name:          "task",
		Aliases:       []string{"t"},
		Summary:       "Manage tasks across statuses BACKLOG/SPRINT/DOING/TESTING/COMPLETED.",
		Description:   "Create, list, query, edit, transition, and dependency-manage tasks within a roadmap.",
		HelpPrinter:   printTaskHelp,
		HasSubcommand: true,
		Prerequisites: []string{"An existing roadmap selected via -r/--roadmap."},
		Subcommands: []Subcommand{
			{
				Name: "list", Aliases: []string{"ls"},
				Summary:     "List tasks (any status; filter with --status).",
				Description: "Returns tasks in the given roadmap across every status.",
				Usage:       "rmp task list -r <roadmap> [filters]",
				HelpPrinter: printTaskListHelp,
				Handler:     taskList,
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--status", Short: "-s", Type: "enum", Enum: "TaskStatus", Description: "Exact status."},
					{Long: "--priority", Short: "-p", Type: "integer", HasRange: true, RangeMin: 0, RangeMax: 9, Description: "Filter: priority >= <min>."},
					{Long: "--severity", Type: "integer", HasRange: true, RangeMin: 0, RangeMax: 9, Description: "Filter: severity >= <min>."},
					{Long: "--type", Short: "-y", Type: "enum", Enum: "TaskType", Description: "Filter by task type."},
					{Long: "--specialists", Short: "-sp", Type: "string", Description: "Filter by specialists (case-insensitive substring)."},
					{Long: "--created-since", Type: "date", Description: "Include tasks created on/after this date (RFC3339 or YYYY-MM-DD)."},
					{Long: "--created-until", Type: "date", Description: "Include tasks created on/before this date."},
					{Long: "--sort", Type: "enum", Enum: "TaskSort", Default: "priority", Description: "Sort field."},
					{Long: "--limit", Short: "-l", Type: "integer", HasRange: true, RangeMin: 1, RangeMax: 100, Default: "100", Description: "Maximum results."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 6},
				Examples: []Example{
					{Title: "All tasks", Cmd: "rmp task list -r myproject", Exit: 0},
					{Title: "Filter BACKLOG p>=7", Cmd: "rmp task list -r myproject --status BACKLOG --priority 7", Exit: 0},
					{Title: "Bad sort", Cmd: "rmp task list -r myproject --sort foo", Stderr: "Error: --sort must be one of: priority, created, status, severity", Exit: 6},
				},
			},
			{
				Name: "create", Aliases: []string{"new"},
				Summary:     "Create a new task (lands in BACKLOG).",
				Description: "Creates a new task in BACKLOG status.",
				Usage:       "rmp task create -r <roadmap> -t <title> -fr <FR> -tr <TR> -ac <AC> [options]",
				HelpPrinter: printTaskCreateHelp,
				Handler:     taskCreate,
				Flags: append(append(append([]Flag{sharedRoadmapFlag()}, taskTextFlags(true)...), taskCommonOptionalFlags()...),
					Flag{Long: "--parent", Type: "integer", Description: "Parent task ID; creates this task as a sub-task of the given parent."},
					helpFlag()),
				Output:      SuccessOutput{Kind: "object", Schema: `{"id": <int>}`, Example: `{"id":42}`},
				SideEffects: SideEffects{Database: "INSERT into tasks and audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 2, 3, 4, 6},
				Examples: []Example{
					{Title: "Create a task", Cmd: `rmp task create -r myproject -t "Fix bug" -fr "User can login" -tr "Update auth" -ac "Login works"`, Stdout: `{"id":42}`, Exit: 0},
					{Title: "Missing required", Cmd: "rmp task create -r myproject", Stderr: "Error: missing required flag: --title", Exit: 2},
				},
			},
			{
				Name:        "get",
				Summary:     "Get tasks by id (CSV, no spaces).",
				Description: "Returns one or more tasks by id; fail-fast on any unknown id.",
				Usage:       "rmp task get -r <roadmap> <task-ids>",
				HelpPrinter: printTaskGetHelp,
				Handler:     taskGet,
				Positional: []Argument{
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer ids."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Single task", Cmd: "rmp task get -r myproject 1", Exit: 0},
					{Title: "Bulk", Cmd: "rmp task get -r myproject 1,3,5", Exit: 0},
				},
			},
			{
				Name:        "next",
				Summary:     "Get next [num] incomplete tasks from the OPEN sprint.",
				Description: "Returns the next N incomplete tasks from the OPEN sprint, in sprint position order.",
				Usage:       "rmp task next -r <roadmap> [num]",
				HelpPrinter: printTaskNextHelp,
				Handler:     taskNext,
				Positional: []Argument{
					{Name: "num", Type: "integer", Required: false, Description: "Maximum tasks to return (default 1, clamped to 100)."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects (SPRINT/DOING/TESTING)."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Next task", Cmd: "rmp task next -r myproject", Exit: 0},
					{Title: "Next 5", Cmd: "rmp task next -r myproject 5", Exit: 0},
				},
			},
			{
				Name:        "edit",
				Summary:     "Edit fields of a task (status NOT editable here).",
				Description: "Edits one or more fields on an existing task. At least one option must be provided.",
				Usage:       "rmp task edit -r <roadmap> <task-id> [options]",
				HelpPrinter: printTaskEditHelp,
				Handler:     taskEdit,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer id of the task."},
				},
				Flags:       append(append(append([]Flag{sharedRoadmapFlag()}, taskTextFlags(false)...), taskCommonOptionalFlags()...), helpFlag()),
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE tasks and audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Change title", Cmd: `rmp task edit -r myproject 42 -t "Updated title"`, Exit: 0},
					{Title: "Change priority", Cmd: "rmp task edit -r myproject 42 -p 8", Exit: 0},
				},
			},
			{
				Name: "remove", Aliases: []string{"rm"},
				Summary:     "Remove task(s) — BACKLOG only, no active subtasks.",
				Description: "Removes one or more tasks. All must be in BACKLOG and free of active subtasks.",
				Usage:       "rmp task remove -r <roadmap> <task-ids>",
				HelpPrinter: printTaskRemoveHelp,
				Handler:     taskRemove,
				Positional: []Argument{
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer ids."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "DELETE from tasks and audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Remove one task", Cmd: "rmp task remove -r myproject 7", Exit: 0},
					{Title: "Remove non-BACKLOG", Cmd: "rmp task remove -r myproject 3", Stderr: "Error: task #3 cannot be deleted — status is SPRINT, must be BACKLOG", Exit: 6},
				},
			},
			{
				Name: "stat", Aliases: []string{"set-status"},
				Summary:     "Set task status (manual transitions; SPRINT is rejected).",
				Description: "Changes the status of one or more tasks; rejected transitions return exit 6.",
				Usage:       "rmp task stat -r <roadmap> <task-ids> <new-status> [--summary <text>]",
				HelpPrinter: printTaskStatHelp,
				Handler:     taskSetStatus,
				Positional: []Argument{
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer ids."},
					{Name: "new-status", Type: "enum", Enum: "TaskStatus", Required: true, Description: "Target status (BACKLOG, DOING, TESTING, COMPLETED)."},
				},
				Flags: []Flag{
					sharedRoadmapFlag(),
					{Long: "--summary", Short: "-s", Type: "string", MaxLength: 4096, Description: "Completion summary (only when new-status is COMPLETED)."},
					helpFlag(),
				},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE tasks + audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Move to DOING", Cmd: "rmp task stat -r myproject 1 DOING", Exit: 0},
					{Title: "Complete with summary", Cmd: `rmp task stat -r myproject 7 COMPLETED --summary "Shipped"`, Exit: 0},
					{Title: "Reject manual SPRINT", Cmd: "rmp task stat -r myproject 1 SPRINT", Stderr: "Error: status SPRINT can only be set automatically via 'sprint add-tasks'", Exit: 6},
				},
			},
			{
				Name:        "reopen",
				Summary:     "Reopen task(s) to BACKLOG, clearing lifecycle timestamps.",
				Description: "Returns one or more tasks to BACKLOG and clears started_at/tested_at/closed_at/completion_summary.",
				Usage:       "rmp task reopen -r <roadmap> <task-ids>",
				HelpPrinter: printTaskReopenHelp,
				Handler:     taskReopen,
				Positional: []Argument{
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer ids."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE tasks + audit log per task; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Reopen one", Cmd: "rmp task reopen -r myproject 7", Exit: 0},
					{Title: "Reopen bulk", Cmd: "rmp task reopen -r myproject 1,3,5", Exit: 0},
				},
			},
			{
				Name: "prio", Aliases: []string{"set-priority"},
				Summary:     "Set task priority (0-9) for one or many tasks.",
				Description: "Sets the priority of one or more tasks to the same value.",
				Usage:       "rmp task prio -r <roadmap> <task-ids> <priority>",
				HelpPrinter: printTaskPrioHelp,
				Handler:     taskSetPriority,
				Positional: []Argument{
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer ids."},
					{Name: "priority", Type: "integer", Required: true, Description: "Integer 0-9 (0 lowest, 9 highest)."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE tasks + audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Bulk reprioritise", Cmd: "rmp task prio -r myproject 1,2,3 8", Exit: 0},
				},
			},
			{
				Name: "sev", Aliases: []string{"set-severity"},
				Summary:     "Set task severity (0-9) for one or many tasks.",
				Description: "Sets the severity of one or more tasks to the same value.",
				Usage:       "rmp task sev -r <roadmap> <task-ids> <severity>",
				HelpPrinter: printTaskSevHelp,
				Handler:     taskSetSeverity,
				Positional: []Argument{
					{Name: "task-ids", Type: "csv:integer", Required: true, Description: "Comma-separated integer ids."},
					{Name: "severity", Type: "integer", Required: true, Description: "Integer 0-9."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE tasks + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Single", Cmd: "rmp task sev -r myproject 5 9", Exit: 0},
				},
			},
			{
				Name:        "assign",
				Summary:     "Add specialist to task (idempotent; stderr note on dup).",
				Description: "Adds <specialist> to the task's specialists list. Idempotent.",
				Usage:       "rmp task assign -r <roadmap> <task-id> <specialist>",
				HelpPrinter: printTaskAssignHelp,
				Handler:     taskAssign,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer task id."},
					{Name: "specialist", Type: "string", Required: true, Description: "Free-form specialist label."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE tasks + audit log; one transaction.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Assign", Cmd: "rmp task assign -r myproject 7 alice", Exit: 0},
				},
			},
			{
				Name:        "unassign",
				Summary:     "Remove specialist from task (idempotent).",
				Description: "Removes <specialist> from the task's specialists list. Idempotent.",
				Usage:       "rmp task unassign -r <roadmap> <task-id> <specialist>",
				HelpPrinter: printTaskUnassignHelp,
				Handler:     taskUnassign,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer task id."},
					{Name: "specialist", Type: "string", Required: true, Description: "Specialist label to remove."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "UPDATE tasks + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Unassign", Cmd: "rmp task unassign -r myproject 7 alice", Exit: 0},
				},
			},
			{
				Name:        "subtasks",
				Summary:     "List direct subtasks (one level; no grand-children).",
				Description: "Lists the direct subtasks of <task-id>.",
				Usage:       "rmp task subtasks -r <roadmap> <task-id>",
				HelpPrinter: printTaskSubtasksHelp,
				Handler:     taskSubtasks,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer task id (parent)."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "List subtasks", Cmd: "rmp task subtasks -r myproject 5", Exit: 0},
				},
			},
			{
				Name:        "add-dep",
				Summary:     "Declare task <id> depends on task <dep-id> (cycles rejected).",
				Description: "Records that <task-id> depends on <blocker-id>. Self-edges and cycles are rejected.",
				Usage:       "rmp task add-dep -r <roadmap> <task-id> <blocker-id>",
				HelpPrinter: printTaskAddDepHelp,
				Handler:     taskAddDep,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer id of the dependent task."},
					{Name: "blocker-id", Type: "integer", Required: true, Description: "Integer id of the task that must complete first."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "INSERT into task_dependencies + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4, 6},
				Examples: []Example{
					{Title: "Add dep", Cmd: "rmp task add-dep -r myproject 10 7", Exit: 0},
				},
			},
			{
				Name:        "remove-dep",
				Summary:     "Remove the dependency edge created by add-dep.",
				Description: "Removes the dependency of <task-id> on <blocker-id>.",
				Usage:       "rmp task remove-dep -r <roadmap> <task-id> <blocker-id>",
				HelpPrinter: printTaskRemoveDepHelp,
				Handler:     taskRemoveDep,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer id of the dependent task."},
					{Name: "blocker-id", Type: "integer", Required: true, Description: "Integer id of the task that was a blocker."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "empty"},
				SideEffects: SideEffects{Database: "DELETE from task_dependencies + audit log.", Filesystem: "None.", Network: "None."},
				Idempotent:  false,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Remove dep", Cmd: "rmp task remove-dep -r myproject 10 7", Exit: 0},
				},
			},
			{
				Name:        "blockers",
				Summary:     "List tasks blocking <id> (incomplete dependencies).",
				Description: "Returns tasks that <task-id> depends on and that are not yet COMPLETED.",
				Usage:       "rmp task blockers -r <roadmap> <task-id>",
				HelpPrinter: printTaskBlockersHelp,
				Handler:     taskBlockers,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer task id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects (incomplete dependencies)."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Blockers", Cmd: "rmp task blockers -r myproject 10", Exit: 0},
				},
			},
			{
				Name:        "blocking",
				Summary:     "List tasks that depend on <id> (reverse of blockers).",
				Description: "Returns tasks that depend on <task-id>.",
				Usage:       "rmp task blocking -r <roadmap> <task-id>",
				HelpPrinter: printTaskBlockingHelp,
				Handler:     taskBlocking,
				Positional: []Argument{
					{Name: "task-id", Type: "integer", Required: true, Description: "Integer task id."},
				},
				Flags:       []Flag{sharedRoadmapFlag(), helpFlag()},
				Output:      SuccessOutput{Kind: "array", Schema: "Array of task objects (downstream dependents)."},
				SideEffects: SideEffects{Database: "Read-only.", Filesystem: "None.", Network: "None."},
				Idempotent:  true,
				ExitCodes:   []int{0, 3, 4},
				Examples: []Example{
					{Title: "Blocking", Cmd: "rmp task blocking -r myproject 7", Exit: 0},
				},
			},
		},
	}
}
