// Code generated by registry_gen.go from github.com/alecthomas/chroma/v2 v2.27.0 lexers/erb.go. DO NOT EDIT.

// This file is a copy, rewritten to build lazily, of chroma source. chroma's
// copyright and permission notice follows; COPYING.chroma is its full COPYING.
//
// Copyright (C) 2017 Alec Thomas
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package highlight

import (
	"strings"

	. "github.com/alecthomas/chroma/v2" // nolint
)

// ERB lexer is Ruby embedded in HTML.
var ERB Lexer

func generatedInitVar020() {
	ERB = Register(DelegatingLexer(HTML, MustNewXMLLexer(
		embedded,
		"embedded/erb.xml",
	).SetConfig(
		&Config{
			Name:      "ERB",
			Aliases:   []string{"erb", "html+erb", "html+ruby", "rhtml"},
			Filenames: []string{"*.erb", "*.html.erb", "*.xml.erb", "*.rhtml"},
			MimeTypes: []string{"application/x-ruby-templating"},
			DotAll:    true,
		},
	).SetAnalyser(func(text string) float32 {
		if strings.Contains(text, "<%=") && strings.Contains(text, "%>") {
			return 0.4
		}
		if strings.Contains(text, "<%") {
			return 0.1
		}
		return 0.0
	})))
}
