// Code generated by registry_gen.go from github.com/alecthomas/chroma/v2 v2.27.0 lexers/gemtext.go. DO NOT EDIT.

// This file is a copy, rewritten to build lazily, of chroma source. chroma's
// copyright and permission notice follows; COPYING.chroma is its full COPYING.
//
// Copyright (C) 2017 Alec Thomas
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package highlight

import (
	. "github.com/alecthomas/chroma/v2" // nolint
)

// Gemtext lexer.
var Gemtext Lexer

func gemtextRules() Rules {
	return Rules{
		"root": {
			{Pattern: `^(#[^#].+\r?\n)`, Type: ByGroups(GenericHeading), Mutator: nil},
			{Pattern: `^(#{2,3}.+\r?\n)`, Type: ByGroups(GenericSubheading), Mutator: nil},
			{Pattern: `^(\* )(.+\r?\n)`, Type: ByGroups(Keyword, Text), Mutator: nil},
			{Pattern: `^(>)(.+\r?\n)`, Type: ByGroups(Keyword, GenericEmph), Mutator: nil},
			{Pattern: "^(```\\r?\\n)([\\w\\W]*?)(^```)(.+\\r?\\n)?", Type: ByGroups(String, Text, String, Comment), Mutator: nil},
			{
				Pattern: "^(```)(\\w+)(\\r?\\n)([\\w\\W]*?)(^```)(.+\\r?\\n)?",
				Type:    UsingByGroup(2, 4, String, String, String, Text, String, Comment),
				Mutator: nil,
			},
			{Pattern: "^(```)(.+\\r?\\n)([\\w\\W]*?)(^```)(.+\\r?\\n)?", Type: ByGroups(String, String, Text, String, Comment), Mutator: nil},
			{Pattern: `^(=>)(\s*)([^\s]+)(\s*)$`, Type: ByGroups(Keyword, Text, NameAttribute, Text), Mutator: nil},
			{Pattern: `^(=>)(\s*)([^\s]+)(\s+)(.+)$`, Type: ByGroups(Keyword, Text, NameAttribute, Text, NameTag), Mutator: nil},
			{Pattern: `(.|(?:\r?\n))`, Type: ByGroups(Text), Mutator: nil},
		},
	}
}

func generatedInitVar021() {
	Gemtext = Register(MustNewLexer(
		&Config{
			Name:      "Gemtext",
			Aliases:   []string{"gemtext", "gmi", "gmni", "gemini"},
			Filenames: []string{"*.gmi", "*.gmni", "*.gemini"},
			MimeTypes: []string{"text/gemini"},
		},
		gemtextRules,
	))
}
