// Code generated by registry_gen.go from github.com/alecthomas/chroma/v2 v2.27.0 lexers/markdown.go. DO NOT EDIT.

// This file is a copy, rewritten to build lazily, of chroma source. chroma's
// copyright and permission notice follows; COPYING.chroma is its full COPYING.
//
// Copyright (C) 2017 Alec Thomas
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package highlight

import (
	"strings"

	. "github.com/alecthomas/chroma/v2" // nolint
)

// Markdown lexer with YAML frontmatter and HTML comment support.
var Markdown Lexer

// markdownLexer wraps the base Markdown lexer to highlight top-of-file YAML frontmatter.
type markdownLexer struct {
	Lexer
}

// Lexes Markdown, highlighting a leading YAML frontmatter block before delegating to Markdown rules.
func (m *markdownLexer) Tokenise(options *TokeniseOptions, text string) (Iterator, error) {
	frontmatter, rest, ok := splitFrontmatter(text)
	if !ok {
		return m.Lexer.Tokenise(options, text)
	}

	yamlLexer := Get("YAML")
	if yamlLexer == nil {
		return m.Lexer.Tokenise(options, text)
	}

	yamlTokens, err := yamlLexer.Tokenise(options, frontmatter)
	if err != nil {
		return nil, err
	}
	markdownTokens, err := m.Lexer.Tokenise(options, rest)
	if err != nil {
		return nil, err
	}
	return Concaterator(yamlTokens, markdownTokens), nil
}

// Extracts a leading YAML frontmatter block if the document starts with one.
func splitFrontmatter(text string) (frontmatter string, rest string, ok bool) {
	if !strings.HasPrefix(text, "---\n") && !strings.HasPrefix(text, "---\r\n") {
		return "", text, false
	}

	lineEnd := strings.IndexByte(text, '\n')
	if lineEnd < 0 {
		return "", text, false
	}
	if strings.TrimSuffix(text[:lineEnd], "\r") != "---" {
		return "", text, false
	}

	for pos := lineEnd + 1; pos < len(text); {
		next := strings.IndexByte(text[pos:], '\n')
		if next < 0 {
			break
		}
		lineEnd = pos + next
		line := strings.TrimSuffix(text[pos:lineEnd], "\r")
		if line == "---" {
			return text[:lineEnd+1], text[lineEnd+1:], true
		}
		pos = lineEnd + 1
	}
	return "", text, false
}

func markdownRules() Rules {
	return Rules{
		"root": {
			{Pattern: `<!--[\w\W]*?-->`, Type: CommentMultiline, Mutator: nil},
			{Pattern: `^(#[^#].+\n)`, Type: ByGroups(GenericHeading), Mutator: nil},
			{Pattern: `^(#{2,6}.+\n)`, Type: ByGroups(GenericSubheading), Mutator: nil},
			{Pattern: `^(\s*)([*-] )(\[[ xX]\])( .+\n)`, Type: ByGroups(Text, Keyword, Keyword, UsingSelf("inline")), Mutator: nil},
			{Pattern: `^(\s*)([*-])(\s)(.+\n)`, Type: ByGroups(Text, Keyword, Text, UsingSelf("inline")), Mutator: nil},
			{Pattern: `^(\s*)([0-9]+\.)( .+\n)`, Type: ByGroups(Text, Keyword, UsingSelf("inline")), Mutator: nil},
			{Pattern: `^(\s*>\s)(.+\n)`, Type: ByGroups(Keyword, GenericEmph), Mutator: nil},
			{Pattern: "^(```\\n)([\\w\\W]*?)(^```$)", Type: ByGroups(String, Text, String), Mutator: nil},
			{
				Pattern: "^(```)(\\w+)(\\n)([\\w\\W]*?)(^```$)",
				Type:    UsingByGroup(2, 4, String, String, String, Text, String),
				Mutator: nil,
			},
			Include("inline"),
		},
		"inline": {
			{Pattern: `<!--[\w\W]*?-->`, Type: CommentMultiline, Mutator: nil},
			{Pattern: `\\.`, Type: Text, Mutator: nil},
			{Pattern: `(\s)(\*|_)((?:(?!\2).)*)(\2)((?=\W|\n))`, Type: ByGroups(Text, GenericEmph, GenericEmph, GenericEmph, Text), Mutator: nil},
			{Pattern: `(\s)((\*\*|__).*?)\3((?=\W|\n))`, Type: ByGroups(Text, GenericStrong, GenericStrong, Text), Mutator: nil},
			{Pattern: `(\s)(~~[^~]+~~)((?=\W|\n))`, Type: ByGroups(Text, GenericDeleted, Text), Mutator: nil},
			{Pattern: "`[^`]+`", Type: LiteralStringBacktick, Mutator: nil},
			{Pattern: `[@#][\w/:]+`, Type: NameEntity, Mutator: nil},
			{Pattern: `(!?\[)([^]]+)(\])(\()([^)]+)(\))`, Type: ByGroups(Text, NameTag, Text, Text, NameAttribute, Text), Mutator: nil},
			{Pattern: `.|\n`, Type: Text, Mutator: nil},
		},
	}
}

func generatedInitVar031() {
	Markdown = Register(&markdownLexer{Lexer: MustNewLexer(
		&Config{
			Name:      "markdown",
			Aliases:   []string{"md", "mkd"},
			Filenames: []string{"*.md", "*.mkd", "*.markdown"},
			MimeTypes: []string{"text/x-markdown"},
		},
		markdownRules,
	)})
}
