// Code generated by registry_gen.go from github.com/alecthomas/chroma/v2 v2.27.0 lexers (initialisation order). DO NOT EDIT.

// This file is a copy, rewritten to build lazily, of chroma source. chroma's
// copyright and permission notice follows; COPYING.chroma is its full COPYING.
//
// Copyright (C) 2017 Alec Thomas
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package highlight

// generatedBuildLexers runs, in the order chroma's lexers package initialises
// them, the initialisers of that package's variables and then its init
// functions, filling GlobalLexerRegistry. It MUST run exactly once.
func generatedBuildLexers() {
	generatedInitVar000()
	generatedInitVar001()
	generatedInitVar002()
	generatedInitVar003()
	generatedInitVar004()
	generatedInitVar005()
	generatedInitVar006()
	generatedInitVar007()
	generatedInitVar008()
	generatedInitVar009()
	generatedInitVar010()
	generatedInitVar011()
	generatedInitVar012()
	generatedInitVar013()
	generatedInitVar014()
	generatedInitVar015()
	generatedInitVar016()
	generatedInitVar017()
	generatedInitVar018()
	generatedInitVar019()
	generatedInitVar020()
	generatedInitVar021()
	generatedInitVar022()
	generatedInitVar023()
	generatedInitVar024()
	generatedInitVar025()
	generatedInitVar026()
	generatedInitVar027()
	generatedInitVar028()
	generatedInitVar029()
	generatedInitVar030()
	generatedInitVar031()
	generatedInitVar032()
	generatedInitVar033()
	generatedInitVar034()
	generatedInitVar035()
	generatedInitVar036()
	generatedInitVar037()
	generatedInitVar038()
	generatedInitVar039()
	generatedInitVar040()
	generatedInitFunc000()
	generatedInitFunc001()
	generatedInitFunc002()
}
