package highlight

import (
	"bytes"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// isGeneratedPath reports whether a slash path relative to the package directory
// is one registry_gen.go owns: its Go files, the copied lexer and style
// definitions, and the copy of chroma's COPYING. It mirrors IsGenerated in
// registry_gen.go, which removes stale files by the same rule.
func isGeneratedPath(rel string) bool {
	switch {
	case rel == "COPYING.chroma":
		return true
	case strings.HasPrefix(rel, "embedded/"), strings.HasPrefix(rel, "styles/"):
		return true
	case !strings.Contains(rel, "/") && strings.HasPrefix(rel, "generated_") && strings.HasSuffix(rel, ".go"):
		return true
	}
	return false
}

// generatedFiles reads every generated file under dir, keyed by its slash path.
func generatedFiles(t *testing.T, dir string) map[string][]byte {
	t.Helper()
	files := map[string][]byte{}
	err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil || d.IsDir() {
			return walkErr
		}
		rel, err := filepath.Rel(dir, p)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if !isGeneratedPath(rel) {
			return nil
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		files[rel] = data
		return nil
	})
	if err != nil {
		t.Fatalf("reading the generated files under %s: %v", dir, err)
	}
	return files
}

// TestGeneratedRegistryIsCurrent is Acceptance Criterion 257 of SPEC/WEB.md: the
// generator, run from the chroma version go.mod pins into an empty directory,
// yields exactly the committed generated files — none missing, none extra, none
// different — so a hand edit, a lexer definition missing from the copy, or a pin
// of chroma to another version fails the test gate until `go generate` is run
// again.
func TestGeneratedRegistryIsCurrent(t *testing.T) {
	out := t.TempDir()
	cmd := exec.Command("go", "run", "registry_gen.go", "-out", out)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("running the registry generator: %v\n%s", err, stderr.String())
	}

	fresh := generatedFiles(t, out)
	committed := generatedFiles(t, ".")
	if len(fresh) == 0 {
		t.Fatal("the generator wrote no file")
	}

	var stale []string
	for rel, want := range fresh {
		got, ok := committed[rel]
		switch {
		case !ok:
			stale = append(stale, rel+": missing from the committed registry")
		case !bytes.Equal(got, want):
			stale = append(stale, rel+": differs from the generator's output")
		}
	}
	for rel := range committed {
		if _, ok := fresh[rel]; !ok {
			stale = append(stale, rel+": committed, but the generator no longer writes it")
		}
	}
	if len(stale) > 0 {
		slices.Sort(stale)
		t.Errorf("the committed lexer registry is stale; run `go generate ./internal/highlight/`:\n  %s",
			strings.Join(stale, "\n  "))
	}
}

// TestGeneratedRegistryCarriesChromaNotice: every generated Go file carries
// chroma's copyright and permission notice, and chroma's COPYING is committed
// beside the copied definitions (SPEC/BUILD.md § Markdown Rendering Rules,
// rule 5).
func TestGeneratedRegistryCarriesChromaNotice(t *testing.T) {
	committed := generatedFiles(t, ".")
	license, ok := committed["COPYING.chroma"]
	if !ok || !bytes.HasPrefix(license, []byte("Copyright (C) 2017 Alec Thomas")) {
		t.Fatal("COPYING.chroma is missing or does not open with chroma's copyright line")
	}
	goFiles := 0
	for rel, data := range committed {
		if !strings.HasSuffix(rel, ".go") {
			continue
		}
		goFiles++
		for _, want := range []string{
			"// Code generated by registry_gen.go from github.com/alecthomas/chroma/v2 ",
			"// Copyright (C) 2017 Alec Thomas",
			"// Permission is hereby granted, free of charge,",
			"// The above copyright notice and this permission notice shall be included in all",
		} {
			if !bytes.Contains(data, []byte(want)) {
				t.Errorf("%s lacks %q", rel, want)
			}
		}
	}
	if goFiles == 0 {
		t.Error("the committed registry holds no generated Go file")
	}
}
