// Package backoff owns Groadmap's bounded exponential-backoff retry policy —
// the whole of it, and the only copy of it in the code.
//
// # What the policy is
//
// One initial attempt, then retries, each preceded by a wait, and a worst-case
// total wait of 2500 ms whichever entry point is used. What an entry point
// varies is the SHAPE of those waits and how far the shape is walked:
//
//   - Retry stops after five retries — six attempts, five waits, 2500 ms of
//     sleeping in the worst case, on the fixed ladder 100, 200, 400, 800, then
//     1000 ms. SPEC/IMPLEMENTATION.md § Concurrency Model / Retry Logic
//     specifies exactly that, for the SQLite layer.
//   - RetryWithin keeps climbing the same fixed ladder until a caller-supplied
//     wait budget is spent, truncating the final rung so that the sleeping
//     totals that budget exactly.
//   - RetryJitteredWithin walks the policy's OTHER published shape, full
//     jitter: each wait is drawn uniformly between zero and a ceiling that
//     doubles from 5 ms and is then held at 250 ms, for at most JitterAttempts
//     attempts and at most the caller's budget of sleeping.
//
// # Why there are two shapes and still one policy
//
// SPEC/IMPLEMENTATION.md § Retry Logic publishes both, and the reason is
// measured rather than stylistic: the two conditions this project retries are
// not the same condition. A SQLite busy result and a held advisory lock are
// waits for a resource somebody else holds, and the fixed ladder is right for
// them. A serialisation conflict inside a graph server is a CONTENTION failure
// whose rate is a function of the load the retries themselves offer, so the
// delay is load shedding and synchronised retries defeat it. Measured against a
// real server under identical load, the fixed ladder exhausted on 0.15% of
// statements and re-sending immediately exhausted on 79.9%; full jitter inside
// the same 2500 ms exhausted on none of 18,000 (rmp task #384).
//
// What the two shapes SHARE is everything except the draw: the loop, the wait
// ordering, the rule that a caller supplies the classifier and nothing more, and
// the maximum total wait. The loop is written once, in retryOver, and every
// entry point feeds it a sequence of waits — so "one policy, two shapes" is a
// property of this file rather than a claim about it. The two shapes are also
// generated by ONE doubling generator with different bounds, because a second
// generator is how #294 would come back at one remove.
//
// Retry is itself expressed as RetryWithin over the SQLite policy's total, and
// the two ladders are asserted to be elementwise identical, so the
// bound-parameterised entry point cannot drift away from the policy it
// generalises.
//
// # Why one caller supplies a budget of its own
//
// SPEC/IMPLEMENTATION.md § Graph Store Concurrency, "Write Contention and
// Recovery" rule 3, takes the LOOP and the LADDER from here for the graph
// store's lock and deliberately does not take the total. The two locks do not
// cover the same thing: no SQLite lock is held across a statement whose cost a
// caller chooses, because Groadmap issues every SQL statement itself, whereas
// the graph store lock is held across the statement its invocation carries. A
// hold may therefore lawfully last a whole statement budget, and a wait sized on
// 2500 ms is shorter than the hold it has to cover. The consequence is measured
// rather than feared: a lawful 4.71-second statement starved a contender that
// gave up after 2.5018 seconds (SPEC/GRAPH.md § Lock Contention).
//
// The budget itself is NOT this package's to hold. It is a property of how long
// that one lock may be held, which only internal/graphlock knows, so that
// package derives it and passes it in. This package owns the waiting and nothing
// about what is being waited for — the same division of labour that leaves
// classification to the caller.
//
// # Why the LOOP lives here, and not merely the numbers
//
// Task #294. Three subsystems ran this policy and each wrote the loop out for
// itself. Two of them — internal/db's retryWithBackoff and internal/commands's
// openWALWriter — read the "5" as a count of ATTEMPTS and skipped the sleep
// before the last one, so they waited four times for 1500 ms while the
// specification, their own comments, and the third site all promised five waits
// for 2500 ms. The 1000 ms delay was never reached by either.
//
// Nothing caught it because the three loops were only ever compared by eye. A
// shared set of CONSTANTS would not have caught it either: the constants agreed
// all along, and the divergence was in the loop that consumed them. So the loop
// is what this package exports. A caller supplies the operation and the
// definition of a retryable failure; it does not get to say how many times or
// how long the ladder is climbed, because that is the decision that drifted.
//
// # Why it is a package of its own
//
// Four production call sites consume the policy — internal/db's
// retryWithBackoff, internal/commands's openWALWriter, internal/web's
// openGraphWALWriter, which joined after #294, and internal/graphlock's
// acquisition — and no one of those packages can host it for the others.
// internal/commands imports the other three; internal/web imports internal/db
// and internal/graphlock; internal/db and internal/graphlock import neither.
// Hosting the loop in any of them would point an import edge the wrong way for
// at least one caller. A leaf is therefore the only home that works, and this
// package imports nothing outside the standard library, so it can be imported
// from anywhere without forming a cycle. It is not folded into internal/utils
// because that package's charter is data handling — JSON, dates, paths, field
// validation — and a retry loop is control flow, which is the same
// separation-of-responsibilities reasoning that gave internal/graphlock its own
// package.
package backoff

import (
	"iter"
	"math/rand/v2"
	"time"
)

const (
	// initialDelay is the wait before the first retry.
	initialDelay = 100 * time.Millisecond

	// maxDelay caps the doubling, so the ladder flattens rather than growing
	// without bound.
	maxDelay = 1000 * time.Millisecond

	// maxRetries counts RETRIES, not attempts, and the distinction is the whole
	// of defect #294. SPEC/IMPLEMENTATION.md § Retry Logic specifies "Maximum
	// retries: 5" and lists five delays; a retry is by definition an attempt
	// after the first, so the policy makes one initial attempt plus five
	// retries — see Attempts — and sleeps exactly once before each retry. It
	// never sleeps after the final attempt, which would buy nothing but delay
	// the failure.
	maxRetries = 5

	// jitterInitialCeiling is the ceiling on the wait before the first retry of
	// the full-jitter shape. It is two orders of magnitude below initialDelay
	// because the two shapes wait for different things: a lock is held for as
	// long as its holder needs it, while the writer that won a serialisation
	// conflict has already committed, so the first thing a loser should do is
	// step out of the contending set briefly rather than wait for anything.
	jitterInitialCeiling = 5 * time.Millisecond

	// jitterMaxCeiling caps the doubling of the jitter ceiling. It is the
	// measured quantity of this shape rather than a round number: a ceiling that
	// stops at 100 ms is WORSE than the fixed ladder at sixty-four writers
	// (1.21-1.48% exhausted against 0.86-1.46%), and a ceiling that does not
	// grow at all collapses there (8.7-9.0%). The cap, and not the
	// randomisation alone, is what sheds the load (rmp task #384;
	// SPEC/IMPLEMENTATION.md § Retry Logic).
	jitterMaxCeiling = 250 * time.Millisecond

	// jitterMaxRetries bounds how many times the full-jitter loop may turn, and
	// it is load-bearing rather than decorative. Under the fixed ladder the
	// total wait bounds the retry count on its own, because every rung is at
	// least initialDelay; under full jitter a draw may be near zero, so a walk
	// bounded only by its total could turn indefinitely against a server that
	// fails instantly.
	jitterMaxRetries = 19
)

// Attempts is the number of times a retried operation is tried in the worst
// case: one initial attempt plus maxRetries retries. It is derived rather than
// written out so it cannot disagree with the policy, and callers use it to
// report how many attempts were made.
//
// It describes Retry. RetryWithin makes as many attempts as its budget pays
// for, which is why no caller of that entry point reports an attempt count.
const Attempts = 1 + maxRetries

// JitterAttempts is the most attempts RetryJitteredWithin can make: one initial
// attempt plus jitterMaxRetries retries. SPEC/IMPLEMENTATION.md § Retry Logic
// states 20 and states why the cap exists at all.
//
// It is a MAXIMUM and not a count, which is where it differs from Attempts. The
// fixed ladder's attempt count and its total wait determine one another, so a
// caller may report either; under full jitter they do not, because the waits are
// drawn. A walk of unlucky long draws spends the budget in fifteen retries and a
// walk of short ones reaches this cap with budget to spare, so a caller that
// wants to say how many attempts were made must count them.
const JitterAttempts = 1 + jitterMaxRetries

// FirstDelay is the wait before the first retry, and so the shortest time this
// policy can delay anything by. It is exported for the assertion that an
// operation did NOT wait: comparing against it keeps that check tied to the
// policy, where naming 100 ms would make the check one more copy of it.
const FirstDelay = initialDelay

// Total returns the worst-case time an exhausted Retry spends sleeping: the sum
// of every delay in the ladder, 2500 ms under the current policy.
//
// It sums the ladder rather than stating a figure, so a change to the policy
// moves this value, every caller's diagnostics, and every test assertion
// together instead of leaving a stale number behind — which is how the four
// waits of #294 went on claiming to be five.
//
// It is also the quantity internal/graphlock adds to its statement budget as the
// allowance for the fixed part of a hold, so this one figure sizes both waits.
func Total() time.Duration {
	var total time.Duration
	for delay := range delays() {
		total += delay
	}
	return total
}

// ladder yields the SHAPE of the policy's delay ladder, without end: 100, 200,
// 400 and 800 ms, then 1000 ms repeating, because the doubling is capped at
// maxDelay.
//
// It is unbounded on purpose. Where the ladder STOPS is the one thing the two
// entry points disagree about, so stopping is decided by the two consumers
// below, while the shape is generated exactly once. Writing a second generator
// for the budgeted walk would recreate defect #294 at one remove: two ladders
// that agree today, are compared only by eye, and drift apart later.
func ladder() iter.Seq[time.Duration] {
	return doubling(initialDelay, maxDelay)
}

// jitterCeilings yields the SHAPE of the full-jitter ceiling, without end: 5,
// 10, 20, 40, 80, 160 ms, then 250 ms repeating, because the doubling is capped
// at jitterMaxCeiling.
//
// It is the same generator as ladder with different bounds, and that sharing is
// deliberate. The two shapes differ in what is done with each term — the fixed
// ladder waits it, full jitter draws below it — and not in how the terms are
// produced, so producing them twice would be two things to keep in step for no
// gain. The ceiling grows monotonically; the DELAY does not, because each one is
// drawn independently and a later draw may be shorter than an earlier one.
func jitterCeilings() iter.Seq[time.Duration] {
	return doubling(jitterInitialCeiling, jitterMaxCeiling)
}

// doubling yields initial, then each previous term doubled, held at limit once
// doubling would pass it. It is unbounded: where a walk STOPS is the consumer's
// decision, and generating the terms exactly once is what keeps the two shapes
// from becoming two policies.
func doubling(initial, limit time.Duration) iter.Seq[time.Duration] {
	return func(yield func(time.Duration) bool) {
		term := initial
		for {
			if !yield(term) {
				return
			}
			term *= 2
			if term > limit {
				term = limit
			}
		}
	}
}

// delays yields the wait before each retry under the SQLite policy, in order:
// 100, 200, 400, 800 and 1000 ms. It is the first maxRetries rungs of ladder,
// and it is what Total sums, so the policy's total can never describe a ladder
// Retry does not climb.
func delays() iter.Seq[time.Duration] {
	return func(yield func(time.Duration) bool) {
		remaining := maxRetries
		for delay := range ladder() {
			if remaining == 0 || !yield(delay) {
				return
			}
			remaining--
		}
	}
}

// delaysWithin yields the wait before each retry of a walk bounded by TIME
// rather than by a retry count: rungs of the same ladder until the cumulative
// sleep reaches bound, with the final rung TRUNCATED so that the sleeping totals
// exactly bound and never more.
//
// Truncating rather than dropping the overshooting rung is what makes the budget
// a promise in both directions: the caller waits the whole of what it asked for,
// and not a millisecond of it is spent after the budget is gone. A bound of zero
// or less yields nothing at all, so the operation is attempted once and never
// slept on — the same rule as "no wait follows the final attempt", reached from
// the other end.
//
// At bound == Total() this yields precisely what delays yields, since the
// SQLite policy's five rungs sum to that total exactly. That equivalence is what
// makes Retry safe to express in terms of RetryWithin, and it is asserted rather
// than argued (TestBudgetedLadderMatchesTheRetryLadder).
func delaysWithin(bound time.Duration) iter.Seq[time.Duration] {
	return func(yield func(time.Duration) bool) {
		var slept time.Duration
		for delay := range ladder() {
			remaining := bound - slept
			if remaining <= 0 {
				return
			}
			if delay > remaining {
				delay = remaining
			}
			if !yield(delay) {
				return
			}
			slept += delay
		}
	}
}

// jitterDelaysWithin yields the wait before each retry of a FULL-JITTER walk:
// for each ceiling of jitterCeilings, a duration drawn uniformly from the closed
// interval [0, ceiling], truncated by whatever is left of bound, and stopping as
// soon as either the budget or retries is spent.
//
// Both bounds are needed and neither is redundant. The budget is what makes the
// shape cost a caller no more than the fixed ladder does; the retry cap is what
// bounds the loop at all, because a draw may be near zero and a walk bounded
// only by its total could turn indefinitely against a server that fails
// instantly. Under the fixed ladder that second bound comes free, since every
// rung is at least initialDelay.
//
// The draw is a parameter rather than a call to the package's randomness so that
// the shape can be walked deterministically in a test — the ONE thing a
// randomised policy cannot assert against the wall clock — while production has
// exactly one draw, drawUpTo, supplied by the single entry point below.
//
// A bound of zero or less, or a retries of zero or less, yields nothing at all,
// so the operation is attempted once and never slept on: the same rule as "no
// wait follows the final attempt", reached from the other end.
func jitterDelaysWithin(bound time.Duration, retries int, draw func(time.Duration) time.Duration) iter.Seq[time.Duration] {
	return func(yield func(time.Duration) bool) {
		var slept time.Duration
		left := retries
		for ceiling := range jitterCeilings() {
			if left <= 0 {
				return
			}
			remaining := bound - slept
			if remaining <= 0 {
				return
			}
			delay := draw(ceiling)
			if delay > remaining {
				delay = remaining
			}
			if !yield(delay) {
				return
			}
			slept += delay
			left--
		}
	}
}

// drawUpTo returns a duration drawn uniformly at random from the CLOSED interval
// [0, ceiling]: zero is a possible draw and so is the ceiling, exactly as
// SPEC/IMPLEMENTATION.md § Retry Logic states. rand.N excludes its argument, so
// the argument is the ceiling plus one tick.
//
// math/rand/v2's top-level functions are safe for concurrent use, which this
// needs: one process may retry several statements at once — the web query bar
// does — and a generator of its own per call would be both wasteful and, if
// seeded from the clock, correlated across exactly the callers this shape exists
// to decorrelate.
//
// The randomness is deliberately the weak kind. Load shedding needs draws that
// are independent of one another, which this gives; it does not need draws an
// adversary cannot predict, nothing about a retry delay is a security boundary,
// and crypto/rand would make every retry in the binary depend on the entropy
// pool for nothing.
func drawUpTo(ceiling time.Duration) time.Duration {
	return rand.N(ceiling + 1) // #nosec G404 -- a retry delay is not a secret: full jitter needs draws independent of one another, not draws an adversary cannot predict
}

// Retry runs try under the policy and returns its first success.
//
// try is called once and then again after each delay in the ladder, for as long
// as it keeps failing with an error retryable accepts — at most Attempts calls
// in all, with a sleep before each retry and none after the last attempt.
//
// Three outcomes, and only three:
//
//   - try succeeds on some attempt: that attempt's value is returned at once,
//     with a nil error, and no further sleeping happens;
//   - try fails with an error retryable REJECTS: that error is returned at once
//     and unwrapped, without sleeping. A constraint violation or a syntax error
//     must not be waited on;
//   - every attempt fails with an error retryable ACCEPTS: the LAST error is
//     returned, unwrapped, after Total of sleeping.
//
// Retry does not wrap, so callers keep their own diagnostics. They also keep
// the ability to tell the last two outcomes apart without extra API: the loop
// stops early only on an error retryable rejects and exhausts only on errors it
// accepts, so asking retryable about the returned error recovers exactly which
// happened.
//
// Classification is the caller's because only the caller knows what contention
// looks like in its subsystem — a SQLite busy/locked result code, a held WAL
// directory lock, a conflicting advisory file lock. Retry owns the timing and
// nothing else.
//
// It is RetryWithin over the SQLite policy's own total, which is the one bound
// under which the budgeted walk and the five-retry walk coincide. Expressing it
// this way leaves a single loop in the package: a separate implementation would
// be the second copy this package exists to prevent.
func Retry[T any](try func() (T, error), retryable func(error) bool) (T, error) {
	return RetryWithin(Total(), try, retryable)
}

// RetryWithin runs try under the same policy as Retry, but bounded by a wait
// budget the caller supplies instead of by the SQLite policy's retry count.
//
// The ladder is the same one, climbed the same way; only its end moves. try is
// called once immediately, then again after each rung of delaysWithin(bound),
// for as long as it keeps failing with an error retryable accepts. The three
// outcomes are Retry's three, unchanged, with one substitution: an exhausted
// call has slept exactly bound rather than exactly Total.
//
// It exists because one caller's wait must be sized against something this
// package cannot see. internal/graphlock holds the graph store's lock across a
// statement whose cost the caller chooses, so how long a hold may lawfully last
// — and therefore how long a waiter must be prepared to wait — is a fact about
// that lock, not about this policy (SPEC/GRAPH.md § Lock Contention;
// SPEC/IMPLEMENTATION.md § Graph Store Concurrency, "Write Contention and
// Recovery" rule 3). What the caller supplies is a duration, never a loop and
// never a ladder: the decision that drifted in #294 stays here.
//
// A bound of zero or less makes exactly one attempt.
func RetryWithin[T any](bound time.Duration, try func() (T, error), retryable func(error) bool) (T, error) {
	return retryOver(delaysWithin(bound), try, retryable)
}

// RetryJitteredWithin runs try under the same policy as RetryWithin, and under
// the policy's OTHER published delay shape: full jitter.
//
// The loop is the same loop, the wait ordering is the same ordering, the
// classifier is still the caller's, and the worst case is still bound of
// sleeping. What differs is the draw. Each wait is taken uniformly at random
// from [0, ceiling], where the ceiling doubles from 5 ms and is then held at
// 250 ms, and the walk stops after JitterAttempts attempts even if the budget is
// not spent — because a draw may be near zero, so the total does not bound the
// loop on its own.
//
// # Why a second shape rather than a second policy
//
// SPEC/IMPLEMENTATION.md § Retry Logic publishes two shapes and one policy, and
// the distinction is the whole of #294's lesson: what drifted then was the LOOP,
// not the constants, so the loop is what stays shared. Adding a shape here is
// the alternative to the two things the graph client must not do — carry a
// private loop of its own, which internal/testenv's gate forbids without a
// deliberate exemption, and move a constant out of this package for one
// caller's benefit.
//
// # Which caller uses it, and why the fixed ladder is wrong for it
//
// internal/graphclient, for a serialisation conflict a graph server reported. A
// conflict is not a wait for a resource: the writer that won has already
// committed, so there is nothing left to wait for, and what the delay buys is
// the loser removing itself from the contending set. The conflict rate is
// therefore a function of the load the retries themselves offer, and identical
// ladders walked by every loser at once keep that load synchronised. Measured
// against a real server (rmp task #384; SPEC/GRAPH.md § Concurrency Inside the
// Server, rule 7), sixteen writers on one node exhausted the fixed ladder on
// 0.15% of statements and exhausted this shape on none of 18,000, inside the
// same 2500 ms and with a shorter worst case.
//
// A bound of zero or less makes exactly one attempt, as RetryWithin's does.
func RetryJitteredWithin[T any](bound time.Duration, try func() (T, error), retryable func(error) bool) (T, error) {
	return retryOver(jitterDelaysWithin(bound, jitterMaxRetries, drawUpTo), try, retryable)
}

// retryOver is THE loop: one initial attempt, then one further attempt after
// each wait the sequence yields, stopping at the first success and at the first
// error the classifier rejects.
//
// Every entry point in this package routes through it, and that is the point.
// The delay SHAPE is what the two published shapes disagree about; the loop, the
// wait ordering and the three outcomes are what they share, and writing them
// once is what makes the sharing structural instead of a claim in a comment.
// Defect #294 was three copies of this loop that agreed by eye and diverged in
// fact.
func retryOver[T any](waits iter.Seq[time.Duration], try func() (T, error), retryable func(error) bool) (T, error) {
	value, err := try()
	if err == nil || !retryable(err) {
		return value, err
	}

	for delay := range waits {
		time.Sleep(delay)

		value, err = try()
		if err == nil || !retryable(err) {
			return value, err
		}
	}

	return value, err
}

// Always accepts every error as retryable. It is the classifier for a caller
// whose operation has exactly one failure mode, contention — opening a
// lock-guarded resource, say — so that such a caller states that fact
// explicitly rather than passing a nil predicate whose meaning has to be
// guessed.
func Always(error) bool { return true }
