package testenv

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"
)

// This file is the regression gate for defect #283.
//
// The defect: agent worktrees live under .claude/worktrees/, each one a full
// second checkout of this repository — 449 files and 16 MB when it was
// measured. The project already knew where they lived, because the security
// gate is invoked as `gosec -exclude-dir=.claude/worktrees` in the Makefile, in
// CLAUDE.md, in SPEC/BUILD.md and in both workflows. git was never told the same
// thing, so `git status` reported `?? .claude/worktrees/` and the whole
// directory was one `git add -A` away from being staged. Both shapes an agent
// scratch directory takes were measured: a plain copy is staged file by file,
// and a linked worktree, which carries its own .git, is staged as a single
// gitlink to a repository that does not exist anywhere else.
//
// The shape of the defect is a PAIR, not a line: one tool is configured to skip
// a path while git is not told to ignore it. Fixing only the one line would
// leave the pair free to reappear the next time a directory is excluded from a
// tool. These tests fail on the pair.
//
// What each test proves:
//
//   - TestPathsExcludedFromAToolAreIgnoredOrDeliberatelyTracked sweeps the
//     repository's own tool configuration for exclusion directives and requires
//     every excluded path that exists in the tree to be git-ignored, or to be
//     named in deliberatelyTracked with a reason. It is derived from the
//     configuration rather than from a hand-written list, so a new
//     `-exclude-dir=` or a new golangci-lint `paths:` entry is covered the day
//     it is added.
//   - TestGeneratedPathsAreIgnoredByThisRepositorysOwnRules requires every
//     tool-generated path to be ignored BY THIS REPOSITORY'S .gitignore, not by
//     a nested ignore file some tool wrote for itself, and requires that nothing
//     is tracked beneath it. The second half is asserted by listing the tracked
//     files under each path, so it cannot be satisfied by an ignore rule that
//     would have no effect on an already-tracked file.
//   - TestMakefileCleanTargetArtefactsAreRegistered ties that register to the
//     Makefile: an artefact the `clean` target deletes but the register does not
//     name fails here, so the register cannot fall behind the build.
//   - TestAgentWorktreeLeavesTheWorkingTreeClean is the defect's own
//     reproduction, run forwards: it creates a real worktree under
//     .claude/worktrees/ and requires `git status` to report nothing new.
//
// Deliberate exclusions from this gate, stated rather than papered over:
//
//   - .idea/ is generated by the IDE and IS tracked (six files, committed since
//     the initial import). It is not named in any tool exclusion, so it is
//     outside the pair this gate is about, and adding an ignore rule for it
//     would change nothing: .gitignore has no effect on a file already in the
//     index. Untracking it is a decision for the repository's owner, not for a
//     bug fix, and .gitignore records the current choice by leaving the Go
//     template's `# .idea/` commented out.
//   - vendor/ is named by golangci-lint's `paths:` and is not ignored, but this
//     project does not vendor and the directory does not exist. The sweep below
//     is silent about a path that is absent — an absent path can be neither
//     tracked nor untracked noise — and speaks the day `go mod vendor` creates
//     one, which is when the decision is actually needed.
//   - A golangci-lint `paths:` entry that is a regular expression rather than a
//     plain path (beyond a leading ^ or a trailing $) is skipped: it names a
//     shape, not a directory, and git ignore rules cannot be checked against it.

// agentWorktreeDir is where agent worktrees are created, relative to the module
// root. It is the path the security gate is told to skip.
const agentWorktreeDir = ".claude/worktrees"

// generatedPath is one file or directory this project's own tooling writes into
// the working tree. A directory entry ends in "/".
type generatedPath struct {
	path     string // slash-separated, relative to the module root
	producer string // what writes it, named for the failure message
}

// generatedPaths is the register of everything the project generates inside its
// own checkout. Every entry must be ignored by this repository's .gitignore and
// must hold no tracked file.
var generatedPaths = []generatedPath{
	{"bin/", "`make build` and `go build -o ./bin/ ./cmd/rmp` (Makefile, CLAUDE.md section 11)"},
	{"coverage/", "`make cover-full`, which writes ./coverage/e2e and ./coverage/unit (Makefile)"},
	{"coverage.out", "`make cover`, and the CI `go test -coverprofile=coverage.out` step"},
	{"tests/__pycache__/", "`python3 tests/run_tests.py` importing the suite's own modules"},
	{".pytest_cache/", "a pytest run over tests/ (tests/README.md records that pytest is not the entry point, but it reaches this suite)"},
	{".claude/agent-memory/", "agent-local memory files, which are not versioned"},
	{agentWorktreeDir + "/", "`git worktree add " + agentWorktreeDir + "/<name>`, each worktree a full second checkout of this repository"},
}

// deliberatelyTracked names the paths that a tool is configured to skip and
// that this repository nevertheless versions on purpose, with the reason. An
// entry here is an exemption from
// TestPathsExcludedFromAToolAreIgnoredOrDeliberatelyTracked, so each one has to
// earn its place: the test below rejects an entry that no longer exists or that
// no longer holds a tracked file.
var deliberatelyTracked = map[string]string{
	".claude": "holds this project's own agent and skill definitions (CLAUDE.md section 7), which are versioned. " +
		"golangci-lint skips the directory because the only Go files under it belong to throwaway worktrees, " +
		"not because its contents are disposable. The generated subdirectories beneath it are ignored individually.",
}

// toolConfigFiles are the files in which this repository configures the tools
// that run over its own tree. Release notes are deliberately absent: they are a
// historical record, and a path named by a past release must not bind the
// present.
var toolConfigFiles = []string{
	"Makefile",
	"CLAUDE.md",
	"SPEC/BUILD.md",
	".gosec.yaml",
	".golangci.yml",
	".github/workflows/ci.yml",
	".github/workflows/release.yml",
}

// excludeDirPattern matches a gosec scope exclusion. The stop set closes the
// value at whitespace, at a quote and at the backtick or closing parenthesis
// that wraps the same invocation when it is quoted inside prose.
var excludeDirPattern = regexp.MustCompile("-exclude-dir=([^\\s'\"`)]+)")

// toolExclusion is one path some tool is configured to skip, and where it was
// found.
type toolExclusion struct {
	path   string // slash-separated, relative to the module root, no trailing slash
	source string // "<file>: <directive>", named for the failure message
}

// TestPathsExcludedFromAToolAreIgnoredOrDeliberatelyTracked asserts that no path
// is skipped by a tool while git is left to report it.
//
// This is the pair the defect is made of. A tool exclusion says "this is not
// project source"; leaving git silent about the same path says the opposite, and
// the disagreement is what let a whole second checkout become stageable.
func TestPathsExcludedFromAToolAreIgnoredOrDeliberatelyTracked(t *testing.T) {
	root := repoRoot(t)

	exclusions := sweepToolExclusions(t, root)
	if len(exclusions) == 0 {
		t.Fatalf("no tool exclusion found in any of %v; the sweep is reading the wrong files "+
			"or the directives changed shape, and this gate would pass without checking anything",
			toolConfigFiles)
	}

	evaluated := 0
	for _, exclusion := range exclusions {
		info, err := os.Stat(filepath.Join(root, filepath.FromSlash(exclusion.path)))
		if err != nil {
			// Absent from the tree: it can be neither tracked nor untracked
			// noise, so there is nothing to decide yet.
			continue
		}
		if _, exempt := deliberatelyTracked[exclusion.path]; exempt {
			continue
		}
		evaluated++

		probe := exclusion.path
		if info.IsDir() {
			probe += "/"
		}
		if source, _ := gitCheckIgnore(t, root, probe); source == "" {
			t.Errorf("%s is excluded from a tool (%s) but git does not ignore it, "+
				"so it is reported as untracked and `git add -A` would stage it. "+
				"Add %s to .gitignore, or record it in deliberatelyTracked with the reason it is versioned.",
				exclusion.path, exclusion.source, probe)
		}
	}

	if evaluated == 0 {
		t.Fatalf("of the %d swept exclusions, not one names a path that both exists in the tree and "+
			"is outside deliberatelyTracked, so this gate checked nothing. Either the sweep stopped "+
			"finding the directives, or every exclusion has been exempted", len(exclusions))
	}
}

// TestDeliberatelyTrackedExemptionsAreStillEarned is the inverse assertion for
// deliberatelyTracked. An exemption that outlives the thing it exempts turns the
// test above into a smaller test without anyone noticing, so each entry must
// still name a path that exists AND that actually holds tracked files.
func TestDeliberatelyTrackedExemptionsAreStillEarned(t *testing.T) {
	root := repoRoot(t)

	paths := make([]string, 0, len(deliberatelyTracked))
	for path := range deliberatelyTracked {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(path))); err != nil {
			t.Errorf("deliberatelyTracked exempts %q, which no longer exists: %v. Remove the exemption.", path, err)
			continue
		}
		if tracked := trackedFilesUnder(t, root, path); len(tracked) == 0 {
			t.Errorf("deliberatelyTracked exempts %q on the grounds that it is versioned, "+
				"but git tracks no file under it. Either the exemption is stale and must be removed, "+
				"or the path should be added to .gitignore.", path)
		}
	}
}

// TestGeneratedPathsAreIgnoredByThisRepositorysOwnRules asserts, for every
// generated path, that this repository's .gitignore ignores it and that nothing
// is tracked beneath it.
//
// The rule's SOURCE is asserted, not merely the outcome. Before this gate,
// .pytest_cache/ was ignored only because pytest writes a .gitignore containing
// `*` inside the directory it creates: an ignore this repository neither owns
// nor can rely on, since it exists only once the tool has run and only for as
// long as the tool keeps writing it. Attribution to .gitignore is what makes the
// repository's own rules sufficient on their own.
//
// The tracked-file half is asserted by listing what git tracks under each path,
// because an ignore rule has no effect on a file that is already in the index —
// which is exactly how a memory file stayed tracked under an ignored directory
// until it was removed (rmp task #279).
func TestGeneratedPathsAreIgnoredByThisRepositorysOwnRules(t *testing.T) {
	root := repoRoot(t)

	// Control: prove the pathspec form used below can find tracked files at
	// all, so an empty result means "nothing tracked here" and never "the
	// question was asked wrongly".
	if control := trackedFilesUnder(t, root, "internal/"); len(control) == 0 {
		t.Fatalf("git tracks no file under internal/, which cannot be true; " +
			"the tracked-file query is broken and every assertion below would pass vacuously")
	}

	for _, generated := range generatedPaths {
		source, rule := gitCheckIgnore(t, root, generated.path)
		switch {
		case source == "":
			t.Errorf("%s is written by %s but git ignores it under no rule at all, "+
				"so it is reported as untracked. Add it to .gitignore.",
				generated.path, generated.producer)
		case source != ".gitignore":
			t.Errorf("%s is ignored by %q (rule %q) rather than by this repository's own .gitignore. "+
				"That file is an artefact of the tool that created the directory, not a rule this "+
				"repository owns, and it disappears with the directory. Name %s in .gitignore.",
				generated.path, source, rule, generated.path)
		}

		if tracked := trackedFilesUnder(t, root, generated.path); len(tracked) > 0 {
			t.Errorf("%s is written by %s, yet git tracks %d file(s) under it: %s. "+
				"An ignore rule does not untrack what is already in the index, so this has to be "+
				"resolved deliberately: remove them from the index, or record the path as versioned on purpose.",
				generated.path, generated.producer, len(tracked), strings.Join(tracked, ", "))
		}
	}
}

// TestMakefileCleanTargetArtefactsAreRegistered pins generatedPaths to the
// Makefile. The `clean` target is the project's own statement of what it leaves
// behind in the working tree, so anything it deletes must be a registered
// generated path — and therefore ignored and untracked by the test above.
func TestMakefileCleanTargetArtefactsAreRegistered(t *testing.T) {
	operands := makefileCleanOperands(t)
	if len(operands) == 0 {
		t.Fatal("the Makefile's `clean` target names no artefact; either the target moved or the " +
			"recipe changed shape, and this gate would pass without checking anything")
	}

	for _, operand := range operands {
		if !registerCovers(operand) {
			t.Errorf("the Makefile's `clean` target deletes %q, which generatedPaths does not cover. "+
				"Register it, so that it is proven ignored and untracked like every other artefact.", operand)
		}
	}
}

// TestAgentWorktreeLeavesTheWorkingTreeClean is the defect's reproduction. It
// creates a real worktree where agents create theirs and requires `git status`
// to report nothing that was not already there.
//
// The assertion is relational — the set of status entries after the worktree
// exists, minus the set before — so a developer's own uncommitted work neither
// masks the defect nor fails the gate.
func TestAgentWorktreeLeavesTheWorkingTreeClean(t *testing.T) {
	root := repoRoot(t)

	if _, err := gitIn(root, "rev-parse", "--verify", "HEAD"); err != nil {
		t.Fatalf("this repository has no HEAD to check out, so the worktree cannot be created: %v", err)
	}

	before := statusEntries(t, root)

	name := "gitignore-gate-" + strconv.FormatInt(time.Now().UnixNano(), 10)
	rel := agentWorktreeDir + "/" + name
	abs := filepath.Join(root, filepath.FromSlash(rel))

	if out, err := gitIn(root, "worktree", "add", "--detach", rel, "HEAD"); err != nil {
		t.Fatalf("creating an agent worktree at %s: %v\n%s", rel, err, out)
	}
	t.Cleanup(func() {
		_, _ = gitIn(root, "worktree", "remove", "--force", rel)
		_, _ = gitIn(root, "worktree", "prune")
		_ = os.RemoveAll(abs)
	})

	// Non-vacuity: a clean status proves nothing unless the worktree really is
	// a second copy of this repository. Both files are versioned at the root,
	// so both must be present in any checkout of it.
	for _, marker := range []string{"go.mod", "Makefile"} {
		if _, err := os.Stat(filepath.Join(abs, marker)); err != nil {
			t.Fatalf("the worktree at %s holds no %s, so it is not a checkout of this repository "+
				"and proves nothing about what git would report: %v", rel, marker, err)
		}
	}

	after := statusEntries(t, root)

	appeared := make([]string, 0, len(after))
	for entry := range after {
		if !before[entry] {
			appeared = append(appeared, entry)
		}
	}
	sort.Strings(appeared)

	if len(appeared) > 0 {
		t.Errorf("a worktree at %s made `git status` report %d new entry/entries: %s. "+
			"The working tree must stay clean while an agent worktree exists, or a `git add -A` "+
			"stages a whole second checkout of this repository.",
			rel, len(appeared), strings.Join(appeared, " | "))
	}

	for entry := range after {
		if strings.Contains(entry, agentWorktreeDir) {
			t.Errorf("`git status` reports %q while a worktree exists at %s; %s/ must be ignored.",
				entry, rel, agentWorktreeDir)
		}
	}
}

// ---------------------------------------------------------------------------
// Sweeps.
// ---------------------------------------------------------------------------

// sweepToolExclusions reads the repository's tool configuration and returns
// every path some tool is told to skip, deduplicated and sorted. A configuration
// file that cannot be read fails the test: a silent read error would shrink the
// sweep to nothing and take the gate with it.
func sweepToolExclusions(t *testing.T, root string) []toolExclusion {
	t.Helper()

	found := map[string]string{} // path -> source

	for _, rel := range toolConfigFiles {
		content, err := os.ReadFile(filepath.Clean(filepath.Join(root, filepath.FromSlash(rel))))
		if err != nil {
			t.Fatalf("reading the tool configuration file %s: %v", rel, err)
		}
		text := string(content)

		for _, match := range excludeDirPattern.FindAllStringSubmatch(text, -1) {
			path := normaliseExclusionPath(match[1])
			if path == "" {
				continue
			}
			if _, seen := found[path]; !seen {
				found[path] = rel + ": -exclude-dir=" + match[1]
			}
		}

		if rel == ".golangci.yml" {
			for _, path := range golangciExcludedPaths(text) {
				if _, seen := found[path]; !seen {
					found[path] = rel + ": an entry under `paths:`"
				}
			}
		}
	}

	paths := make([]string, 0, len(found))
	for path := range found {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	exclusions := make([]toolExclusion, 0, len(paths))
	for _, path := range paths {
		exclusions = append(exclusions, toolExclusion{path: path, source: found[path]})
	}
	return exclusions
}

// golangciRegexMeta are the regular-expression characters that turn a
// golangci-lint `paths:` entry into a shape rather than a path. A leading ^ and
// a trailing $ are stripped before this check, so an entry still carrying any of
// these is a pattern and is skipped.
//
// "." is deliberately absent. It is a regex metacharacter, but in a path it is
// overwhelmingly a literal — ".claude" is the entry this whole gate turns on —
// and treating it as a pattern made the sweep skip the very directory the
// defect lives under. An entry that really is a regex reaches for "\." instead,
// and the backslash IS in this set.
const golangciRegexMeta = `\*?[]()|+{}^$`

// golangciExcludedPaths returns the plain directory paths named by the
// `paths:` lists in a .golangci.yml document. It is a targeted scan rather than
// a YAML parse: the module has no YAML dependency, and this gate must not add
// one to read five list items.
func golangciExcludedPaths(document string) []string {
	lines := strings.Split(document, "\n")
	paths := make([]string, 0, len(lines))

	for index, line := range lines {
		if strings.TrimSpace(line) != "paths:" {
			continue
		}
		keyIndent := len(line) - len(strings.TrimLeft(line, " "))

		for _, item := range lines[index+1:] {
			trimmed := strings.TrimSpace(item)
			if trimmed == "" {
				break
			}
			itemIndent := len(item) - len(strings.TrimLeft(item, " "))
			if itemIndent <= keyIndent || !strings.HasPrefix(trimmed, "- ") {
				break
			}

			value := strings.Trim(strings.TrimSpace(strings.TrimPrefix(trimmed, "- ")), `"'`)
			value = strings.TrimSuffix(strings.TrimPrefix(value, "^"), "$")
			if value == "" || strings.ContainsAny(value, golangciRegexMeta) {
				continue
			}
			if path := normaliseExclusionPath(value); path != "" {
				paths = append(paths, path)
			}
		}
	}
	return paths
}

// makefileCleanOperands returns the paths the Makefile's `clean` target deletes,
// relative to the module root.
func makefileCleanOperands(t *testing.T) []string {
	t.Helper()

	lines := strings.Split(readRepoFileAt(t, "Makefile"), "\n")

	start := -1
	for index, line := range lines {
		if strings.HasPrefix(line, "clean:") {
			start = index
			break
		}
	}
	if start < 0 {
		t.Fatal("the Makefile declares no `clean` target, so this gate cannot read what the build leaves behind")
	}

	operands := make([]string, 0, len(lines))
	for _, line := range lines[start+1:] {
		if !strings.HasPrefix(line, "\t") {
			break
		}
		fields := strings.Fields(strings.TrimPrefix(line, "\t"))
		if len(fields) == 0 || strings.TrimPrefix(fields[0], "@") != "rm" {
			continue
		}
		for _, field := range fields[1:] {
			if strings.HasPrefix(field, "-") {
				continue
			}
			if path := normaliseExclusionPath(field); path != "" {
				operands = append(operands, path)
			}
		}
	}

	sort.Strings(operands)
	return operands
}

// registerCovers reports whether generatedPaths accounts for a path: either as
// that exact file, or as a directory the path lies within.
func registerCovers(path string) bool {
	for _, generated := range generatedPaths {
		if !strings.HasSuffix(generated.path, "/") {
			if generated.path == path {
				return true
			}
			continue
		}
		if strings.HasPrefix(path+"/", generated.path) {
			return true
		}
	}
	return false
}

// normaliseExclusionPath reduces a path as it is written in a configuration file
// to the slash-separated, module-root-relative form the rest of this file uses:
// no "./" prefix, no "$(CURDIR)/" prefix, no trailing slash.
func normaliseExclusionPath(raw string) string {
	path := strings.TrimSpace(raw)
	path = strings.TrimPrefix(path, "$(CURDIR)/")
	path = strings.TrimPrefix(path, "./")
	path = strings.TrimSuffix(path, "/")
	if path == "." || path == ".." {
		return ""
	}
	return path
}

// ---------------------------------------------------------------------------
// git.
// ---------------------------------------------------------------------------

// gitIn runs git in dir and returns its combined output with the trailing
// newline removed.
func gitIn(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return strings.TrimRight(string(out), "\n"), err
}

// gitCheckIgnore reports which ignore rule covers path, as git itself resolves
// it: the source file of the winning rule and the rule's pattern. Both are empty
// when nothing ignores the path.
//
// The index is deliberately consulted (no --no-index), because that is what
// `git status` does: a tracked path is never reported as ignored, which is the
// distinction that makes TestGeneratedPathsAreIgnoredByThisRepositorysOwnRules
// meaningful for a path someone committed before the rule existed.
func gitCheckIgnore(t *testing.T, root, path string) (source, rule string) {
	t.Helper()

	cmd := exec.Command("git", "check-ignore", "--verbose", "--", path)
	cmd.Dir = root
	out, err := cmd.Output()
	text := strings.TrimRight(string(out), "\n")

	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && exitErr.ExitCode() == 1 {
			return "", "" // git's answer for "no rule covers this path"
		}
		t.Fatalf("git check-ignore --verbose -- %s: %v\n%s", path, err, text)
	}

	line, _, _ := strings.Cut(text, "\n")
	field, _, found := strings.Cut(line, "\t")
	if !found {
		t.Fatalf("git check-ignore reported %q for %s, which is not the documented "+
			"<source>:<line>:<pattern>\\t<path> form", line, path)
	}
	parts := strings.SplitN(field, ":", 3)
	if len(parts) != 3 {
		t.Fatalf("git check-ignore reported %q for %s, which is not the documented "+
			"<source>:<line>:<pattern> form", field, path)
	}
	return parts[0], parts[2]
}

// trackedFilesUnder lists the files git tracks under a module-root-relative
// path. An empty result is the proof that an ignore rule is not covering for
// something already in the index.
func trackedFilesUnder(t *testing.T, root, path string) []string {
	t.Helper()

	out, err := gitIn(root, "ls-files", "--", path)
	if err != nil {
		t.Fatalf("git ls-files -- %s: %v\n%s", path, err, out)
	}
	if out == "" {
		return nil
	}
	return strings.Split(out, "\n")
}

// statusEntries returns the porcelain status of the working tree as a set.
// --untracked-files=all expands an ordinary untracked directory into its files,
// so nothing hides behind a collapsed entry; a directory holding its own .git,
// as a linked worktree does, is one entry either way, and one entry is already
// one too many.
func statusEntries(t *testing.T, root string) map[string]bool {
	t.Helper()

	out, err := gitIn(root, "status", "--porcelain", "--untracked-files=all")
	if err != nil {
		t.Fatalf("git status --porcelain --untracked-files=all: %v\n%s", err, out)
	}

	entries := map[string]bool{}
	if out == "" {
		return entries
	}
	for _, line := range strings.Split(out, "\n") {
		entries[line] = true
	}
	return entries
}
